// Archivo generado por scripts/update-vision-models.ts desde models.dev.
// No editar a mano: correr `bun run update:models`.
// Generado: 2026-09-27
// Valores de esfuerzo (reasoning_options tipo "effort"); [] = el modelo
// solo tiene budget_tokens o toggle (ver src/config/effort.ts).

export const MODEL_EFFORT: Record<string, Record<string, string[]>> = {
  groq: {
    'allam-2-7b': [],
    'canopylabs/orpheus-arabic-saudi': [],
    'canopylabs/orpheus-v1-english': [],
    'groq/compound': [],
    'groq/compound-mini': [],
    'llama-3.1-8b-instant': [],
    'llama-3.3-70b-versatile': [],
    'meta-llama/llama-prompt-guard-2-22m': [],
    'meta-llama/llama-prompt-guard-2-86m': [],
    'openai/gpt-oss-120b': ['low', 'medium', 'high'],
    'openai/gpt-oss-20b': ['low', 'medium', 'high'],
    'openai/gpt-oss-safeguard-20b': ['low', 'medium', 'high'],
    'qwen/qwen3.6-27b': ['none', 'default'],
    'qwen/qwen3.8-27b': ['none', 'default', 'low', 'medium', 'high'],
    'whisper-large-v3': [],
    'whisper-large-v3-turbo': [],
  },
  openai: {
    'chatgpt-image-latest': [],
    'gpt-3.5-turbo': [],
    'gpt-4': [],
    'gpt-4-turbo': [],
    'gpt-4.1': [],
    'gpt-4.1-mini': [],
    'gpt-4.1-nano': [],
    'gpt-4o': [],
    'gpt-4o-2024-05-13': [],
    'gpt-4o-2024-08-06': [],
    'gpt-4o-2024-11-20': [],
    'gpt-4o-mini': [],
    'gpt-5': ['minimal', 'low', 'medium', 'high'],
    'gpt-5-mini': ['minimal', 'low', 'medium', 'high'],
    'gpt-5-nano': ['minimal', 'low', 'medium', 'high'],
    'gpt-5-pro': ['high'],
    'gpt-5.1': ['none', 'low', 'medium', 'high'],
    'gpt-5.2': ['none', 'low', 'medium', 'high', 'xhigh'],
    'gpt-5.2-chat-latest': ['medium'],
    'gpt-5.2-pro': ['medium', 'high', 'xhigh'],
    'gpt-5.3-chat-latest': [],
    'gpt-5.3-codex': ['none', 'low', 'medium', 'high', 'xhigh'],
    'gpt-5.3-codex-spark': ['none', 'low', 'medium', 'high', 'xhigh'],
    'gpt-5.4': ['none', 'low', 'medium', 'high', 'xhigh'],
    'gpt-5.4-mini': ['none', 'low', 'medium', 'high', 'xhigh'],
    'gpt-5.4-nano': ['none', 'low', 'medium', 'high', 'xhigh'],
    'gpt-5.4-pro': ['medium', 'high', 'xhigh'],
    'gpt-5.5': ['none', 'low', 'medium', 'high', 'xhigh'],
    'gpt-5.5-pro': ['medium', 'high', 'xhigh'],
    'gpt-5.6': ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    'gpt-5.6-luna': ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    'gpt-5.6-sol': ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    'gpt-5.6-terra': ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    'gpt-6-astra': ['low', 'medium', 'high', 'xhigh', 'max'],
    'gpt-6-luna': ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    'gpt-6-sol': ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    'gpt-image-1': [],
    'gpt-image-1-mini': [],
    'gpt-image-1.5': [],
    'gpt-image-2': [],
    'gpt-realtime-2.1': ['minimal', 'low', 'medium', 'high', 'xhigh'],
    o1: ['low', 'medium', 'high'],
    'o1-pro': ['low', 'medium', 'high'],
    o3: ['low', 'medium', 'high'],
    'o3-mini': ['low', 'medium', 'high'],
    'o3-pro': ['low', 'medium', 'high'],
    'o4-mini': ['low', 'medium', 'high'],
    'text-embedding-3-large': [],
    'text-embedding-3-small': [],
    'text-embedding-ada-002': [],
  },
  anthropic: {
    'claude-fable-5': ['low', 'medium', 'high', 'xhigh', 'max'],
    'claude-fable-5-1': ['low', 'medium', 'high', 'xhigh', 'max'],
    'claude-haiku-4-5': [],
    'claude-haiku-4-5-20251001': [],
    'claude-opus-4-5': ['low', 'medium', 'high'],
    'claude-opus-4-5-20251101': ['low', 'medium', 'high'],
    'claude-opus-4-6': ['low', 'medium', 'high', 'max'],
    'claude-opus-4-7': ['low', 'medium', 'high', 'xhigh', 'max'],
    'claude-opus-4-8': ['low', 'medium', 'high', 'xhigh', 'max'],
    'claude-opus-5': ['low', 'medium', 'high', 'xhigh', 'max'],
    'claude-opus-5-5': ['low', 'medium', 'high', 'xhigh', 'max'],
    'claude-sonnet-4-5': [],
    'claude-sonnet-4-5-20250929': [],
    'claude-sonnet-4-6': ['low', 'medium', 'high', 'max'],
    'claude-sonnet-5': ['low', 'medium', 'high', 'xhigh', 'max'],
  },
  gemini: {
    'deep-research-max-preview-04-2026': [],
    'deep-research-preview-04-2026': [],
    'gemini-2.5-computer-use-preview-10-2025': [],
    'gemini-2.5-flash': [],
    'gemini-2.5-flash-image': [],
    'gemini-2.5-flash-lite': [],
    'gemini-2.5-flash-preview-tts': [],
    'gemini-2.5-pro': [],
    'gemini-2.5-pro-preview-tts': [],
    'gemini-3-flash-preview': ['minimal', 'low', 'medium', 'high'],
    'gemini-3-pro-image': ['low', 'high'],
    'gemini-3-pro-image-preview': [],
    'gemini-3.1-flash-image': ['minimal', 'high'],
    'gemini-3.1-flash-image-preview': ['minimal', 'high'],
    'gemini-3.1-flash-lite': ['minimal', 'low', 'medium', 'high'],
    'gemini-3.1-flash-lite-image': ['minimal', 'high'],
    'gemini-3.1-flash-lite-preview': ['minimal', 'low', 'medium', 'high'],
    'gemini-3.1-flash-live-preview': ['minimal', 'low', 'medium', 'high'],
    'gemini-3.1-flash-tts-preview': [],
    'gemini-3.1-pro-preview': ['low', 'medium', 'high'],
    'gemini-3.1-pro-preview-customtools': ['low', 'medium', 'high'],
    'gemini-3.5-flash': ['minimal', 'low', 'medium', 'high'],
    'gemini-3.5-flash-lite': ['minimal', 'low', 'medium', 'high'],
    'gemini-3.5-live-translate-preview': [],
    'gemini-3.6-flash': ['minimal', 'low', 'medium', 'high'],
    'gemini-3.7-flash': ['low', 'medium', 'high'],
    'gemini-3.8-flash': ['low', 'medium', 'high'],
    'gemini-embedding-001': [],
    'gemini-embedding-2': [],
    'gemini-flash-latest': ['low', 'medium', 'high'],
    'gemini-flash-lite-latest': ['minimal', 'low', 'medium', 'high'],
    'gemini-omni-flash-preview': [],
    'gemma-4-26b-a4b-it': [],
    'gemma-4-31b-it': [],
    'lyria-3-clip-preview': [],
    'lyria-3-pro-preview': [],
    'veo-3.1-fast-generate-preview': [],
    'veo-3.1-generate-preview': [],
    'veo-3.1-lite-generate-preview': [],
  },
  opencodezen: {
    'big-pickle': [],
    'claude-3-5-haiku': [],
    'claude-fable-5': ['low', 'medium', 'high', 'xhigh', 'max'],
    'claude-fable-5-1': ['low', 'medium', 'high', 'xhigh', 'max'],
    'claude-haiku-4-5': [],
    'claude-opus-4-1': [],
    'claude-opus-4-5': ['low', 'medium', 'high'],
    'claude-opus-4-6': ['low', 'medium', 'high', 'max'],
    'claude-opus-4-7': ['low', 'medium', 'high', 'xhigh', 'max'],
    'claude-opus-4-8': ['low', 'medium', 'high', 'xhigh', 'max'],
    'claude-opus-5': ['low', 'medium', 'high', 'xhigh', 'max'],
    'claude-opus-5-5': ['low', 'medium', 'high', 'xhigh', 'max'],
    'claude-sonnet-4': [],
    'claude-sonnet-4-5': [],
    'claude-sonnet-4-6': ['low', 'medium', 'high', 'max'],
    'claude-sonnet-5': ['low', 'medium', 'high', 'xhigh', 'max'],
    'deepseek-v4-flash': ['low', 'high', 'max'],
    'deepseek-v4-flash-free': ['low', 'high', 'max'],
    'deepseek-v4-flash-vision-exp': ['low', 'high', 'max'],
    'deepseek-v4-pro': ['high', 'max'],
    'deepseek-v4.1-flash': ['low', 'high', 'max'],
    'gemini-3-flash': ['minimal', 'low', 'medium', 'high'],
    'gemini-3-pro': ['low', 'high'],
    'gemini-3.1-pro': ['low', 'medium', 'high'],
    'gemini-3.5-flash': ['minimal', 'low', 'medium', 'high'],
    'gemini-3.5-flash-lite': ['minimal', 'low', 'medium', 'high'],
    'gemini-3.6-flash': ['minimal', 'low', 'medium', 'high'],
    'gemini-3.7-flash': ['low', 'medium', 'high'],
    'gemini-3.8-flash': ['low', 'medium', 'high'],
    'glm-4.6': [],
    'glm-4.7': [],
    'glm-4.7-free': [],
    'glm-5': [],
    'glm-5-free': [],
    'glm-5.1': [],
    'glm-5.2': ['high', 'max'],
    'glm-5.3': ['low', 'high', 'max'],
    'glm-5.3-flash': ['low', 'high', 'max'],
    'gpt-5': ['minimal', 'low', 'medium', 'high'],
    'gpt-5-codex': ['low', 'medium', 'high'],
    'gpt-5-nano': ['minimal', 'low', 'medium', 'high'],
    'gpt-5.1': ['none', 'low', 'medium', 'high'],
    'gpt-5.1-codex': ['low', 'medium', 'high'],
    'gpt-5.1-codex-max': ['low', 'medium', 'high', 'xhigh'],
    'gpt-5.1-codex-mini': ['low', 'medium', 'high'],
    'gpt-5.2': ['none', 'low', 'medium', 'high', 'xhigh'],
    'gpt-5.2-codex': ['low', 'medium', 'high', 'xhigh'],
    'gpt-5.3-codex': ['none', 'low', 'medium', 'high', 'xhigh'],
    'gpt-5.3-codex-spark': ['low', 'medium', 'high', 'xhigh'],
    'gpt-5.4': ['none', 'low', 'medium', 'high', 'xhigh'],
    'gpt-5.4-mini': ['none', 'low', 'medium', 'high', 'xhigh'],
    'gpt-5.4-nano': ['none', 'low', 'medium', 'high', 'xhigh'],
    'gpt-5.4-pro': ['medium', 'high', 'xhigh'],
    'gpt-5.5': ['none', 'low', 'medium', 'high', 'xhigh'],
    'gpt-5.5-pro': ['medium', 'high', 'xhigh'],
    'gpt-5.6-luna': ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    'gpt-5.6-sol': ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    'gpt-5.6-terra': ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    'gpt-6-astra': ['low', 'medium', 'high', 'xhigh', 'max'],
    'gpt-6-luna': ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    'gpt-6-sol': ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    'grok-4.5': ['low', 'medium', 'high'],
    'grok-4.6': ['low', 'medium', 'high', 'xhigh'],
    'grok-4.7': ['low', 'medium', 'high', 'xhigh'],
    'grok-build-0.1': [],
    'grok-code': [],
    'hy3-free': ['low', 'medium', 'high'],
    'hy3-preview-free': [],
    'kimi-k2': [],
    'kimi-k2-thinking': [],
    'kimi-k2.5': [],
    'kimi-k2.5-free': [],
    'kimi-k2.6': [],
    'kimi-k2.7-code': [],
    'kimi-k3': ['max'],
    'laguna-s-2.1-free': ['low', 'medium', 'high'],
    'ling-2.6-flash-free': [],
    'ling-3.0-flash-fin-free': [],
    'ling-3.0-flash-free': ['low', 'medium', 'high'],
    'ling-3.0-tiny-free': [],
    'longcat-2.0-free': [],
    'longcat-2.5-preview-free': [],
    'mimo-v2-flash-free': [],
    'mimo-v2-omni-free': [],
    'mimo-v2-pro-free': [],
    'mimo-v2.5-free': [],
    'mimo-v2.6-flash-free': [],
    'minimax-m2.1': [],
    'minimax-m2.1-free': [],
    'minimax-m2.5': [],
    'minimax-m2.5-free': [],
    'minimax-m2.7': [],
    'minimax-m3': [],
    'minimax-m3-free': [],
    'muse-spark-1.2': ['minimal', 'low', 'medium', 'high', 'xhigh'],
    'muse-spark-1.2-contributor-free': [
      'minimal',
      'low',
      'medium',
      'high',
      'xhigh',
    ],
    'muse-spark-1.3': ['minimal', 'low', 'medium', 'high', 'xhigh'],
    'muse-spark-1.3-contributor-free': [
      'minimal',
      'low',
      'medium',
      'high',
      'xhigh',
    ],
    'nemotron-3-super-free': [],
    'nemotron-3-ultra-free': [],
    'nemotron-3.5-lightning-free': [],
    'north-mini-code-free': ['none', 'high'],
    'qwen3-coder': [],
    'qwen3.5-plus': [],
    'qwen3.6-plus': [],
    'qwen3.6-plus-free': [],
    'qwen3.8-flash': ['low', 'medium', 'xhigh'],
    'qwen3.8-max': [],
    'ring-2.6-1t-free': [],
    'space-bunny-free': ['low', 'medium', 'high', 'xhigh', 'max'],
    'trinity-large-preview-free': [],
    'x-preview-f-free': ['low', 'high', 'max'],
  },
  opengo: {
    'deepseek-v4-flash': ['low', 'high', 'max'],
    'deepseek-v4-flash-vision-exp': ['low', 'high', 'max'],
    'deepseek-v4-pro': ['high', 'max'],
    'deepseek-v4.1-flash': ['low', 'high', 'max'],
    'glm-5': [],
    'glm-5.1': [],
    'glm-5.2': ['high', 'max'],
    'glm-5.3': ['low', 'high', 'max'],
    'glm-5.3-flash': ['low', 'high', 'max'],
    'gpt-5.6-luna': ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    'gpt-6-luna': ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    'grok-4.5': ['low', 'medium', 'high'],
    'grok-4.6': ['low', 'medium', 'high', 'xhigh'],
    'grok-4.7': ['low', 'medium', 'high', 'xhigh'],
    hy3: ['none', 'low', 'high'],
    'hy4-preview': ['none', 'high'],
    'kimi-k2.5': [],
    'kimi-k2.6': [],
    'kimi-k2.7-code': [],
    'kimi-k3': ['max'],
    'longcat-2.0': [],
    'longcat-2.5-preview-free': [],
    'mimo-v2-omni': [],
    'mimo-v2-pro': [],
    'mimo-v2.5': [],
    'mimo-v2.5-pro': [],
    'mimo-v2.6-flash': [],
    'mimo-v2.6-pro': [],
    'minimax-m2.5': [],
    'minimax-m2.7': [],
    'minimax-m3': [],
    'muse-spark-1.2-contributor': ['minimal', 'low', 'medium', 'high', 'xhigh'],
    'muse-spark-1.3-contributor': ['minimal', 'low', 'medium', 'high', 'xhigh'],
    'omen-alpha': ['low', 'high'],
    'ox-alpha-free': ['low', 'high', 'max'],
    'qwen3.5-plus': [],
    'qwen3.6-plus': [],
    'qwen3.7-max': [],
    'qwen3.7-plus': [],
    'qwen3.8-flash': ['low', 'medium', 'xhigh'],
    'qwen3.8-max': ['low', 'medium', 'xhigh'],
    'space-bunny-free': ['low', 'medium', 'high', 'xhigh', 'max'],
  },
}
